name: 'Named Branches'
author: 'Julian Berman'
description: 'hg-style branch naming, implemented via automatic git notes'
branding:
  icon: 'git-branch'
  color: 'red'

inputs:
  github_token:
    description: 'the GITHUB_TOKEN secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Add the Branch
      env:
        GIT_AUTHOR_NAME: "Named Branches GitHub Action"
        GIT_COMMITTER_NAME: "Named Branches GitHub Action"
      run: |
        git fetch origin refs/notes/branch:refs/notes/branch || true
        git notes --ref refs/notes/branch add -m "${{ github.ref }}"
      shell: bash

    - name: Push the new notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: git push origin refs/notes/branch:refs/notes/branch
      shell: bash
