name: 'Named Branches'
author: 'Julian Berman'
description: 'hg-style branch naming, implemented via automatic git notes'
branding:
  icon: 'git-branch'
  color: 'red'

inputs:
  github_token:
    description: 'the GITHUB_TOKEN secret'
    required: true

  ref:
    description: 'git ref to commit branch names to'
    required: false
    default: 'refs/notes/branch'

runs:
  using: 'composite'
  steps:
    - name: Add the Branch
      env:
        GIT_AUTHOR_NAME: "Named Branches GitHub Action"
        GIT_COMMITTER_NAME: "Named Branches GitHub Action"
      run: |
        git fetch origin notes/branch
        git notes --ref "${{ inputs.ref }}" add -m "${{ github.ref }}"
      shell: bash

    - name: Push the new notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: git push origin ${{ inputs.ref }}:${{ inputs.ref }}
      shell: bash
