name: 'Named Branches'
author: 'Julian Berman'
description: 'hg-style branch naming, implemented via automatic git notes'
branding:
  icon: 'git-branch'
  color: 'red'

inputs:
  github_token:
    description: 'the GITHUB_TOKEN secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Identify where we are
      # refs/someone/their-repo/their-branch when we're receiving a PR
      # otherwise
      # refs/heads/branch-name for pushes inside this repository
      run: |
        if [ -n "${{ github.head_ref }}" ]; then
          export CURRENT_BRANCH="refs/${{ github.repository }}/${{ github.head_ref }}"
        else
          export CURRENT_BRANCH="${{ github.ref }}"
        fi
        echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
      shell: bash
    - name: Add the Branch
      env:
        GIT_AUTHOR_NAME: "Named Branches GitHub Action"
        GIT_COMMITTER_NAME: "Named Branches GitHub Action"
      run: |
        set -e
        git config user.name "Named Branches GitHub Action"
        git config user.email "actions@users.noreply.github.com"
        git fetch origin refs/notes/branch:refs/notes/branch || true
        for each in $(git rev-list HEAD); do
          git notes --ref refs/notes/branch show "$each" >/dev/null 2>&1 && break
          git notes --ref refs/notes/branch add -m "$CURRENT_BRANCH" "$each"
        done
      shell: bash

    - name: Push the new notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: git push origin refs/notes/branch:refs/notes/branch
      shell: bash
