name: 'Named Branches'
on: push
jobs:
  named-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Julian/named-branch-action@main
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
